services:
  portas-abertas:
    build: .
    ports:
      - "20:20/tcp"
      - "21:21/tcp"
      - "22:22/tcp"
      - "23:23/tcp"
      - "25:25/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "110:110/tcp"
      - "143:143/tcp"
      - "389:389/tcp"
      - "445:445/tcp"
      - "1433:1433/tcp"
      - "3306:3306/tcp"
      - "3389:3389/tcp"
      - "5432:5432/tcp"
      - "8080:8080/tcp"
      - "161:161/udp"
      - "67:67/udp"
      - "68:68/udp"